[mosip_env]
host_url='https://qa3.mosip.net'

[mosip_websub]
publisher='CREDENTIAL_SERVICE'
topic='mpartner-default-auth/CREDENTIAL_ISSUED'

[input]
file_path='/opt/taheer-mos/mosip/ida-data-seeder/auth-data-seeder/data-seeder/sample/test-import-qa3.csv'
separator='|'

# Note Providing full file path to take it to outside application.
[random_generator]
salt_start_index=0
salt_max_index=1000
salt_file_store='/opt/taheer-mos/mosip/ida-data-seeder/auth-data-seeder/data-seeder/secrets-store/secret_salts-qa3.txt'
salt_bytes_size=16

zk_keys_start_index=10001
zk_keys_max_index=15000
zk_keys_file_store='/opt/taheer-mos/mosip/ida-data-seeder/auth-data-seeder/data-seeder/secrets-store/zk_keys.txt'
zk_key_bytes_size=32

[key_cloak]
url='https://qa3.mosip.net/keycloak/auth/realms/mosip/protocol/openid-connect/token'
user_name='mosip-creser-client'
user_secret=''

[ida]
public_key='/home/mahammedtaheer/Desktop/keys/qa3/ida-cred-serv.cer'
websub_secret=''
cred_service_url='https://qa3.mosip.net/idauthentication/v1/internal/callback/idchange/credential_issued/'
is_ida_ver_115=true

[datashare]
create_url='https://qa3.mosip.net/v1/datashare/create'
policy_id='mpolicy-default-auth'
partner_id='mpartner-default-auth'
format_id='http://mosip.io/credentials/'
schema_name='MOSIPVerifiableCredential'
format_issuer='https://mosip.io/issuers/'
issuer='mpartner-default-auth'
timestamp_format='%Y-%m-%dT%H:%M:%S'
sign_p12_file='/home/mahammedtaheer/Desktop/keys/local-test-partner/partner.p12'
p12_pwd=''
replace_external_url=false

